# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fdb29b07f8cd9f90d7bf7eed56a047ea738efcad0a40d6f037ada36b4c12e46a251c5cfc53b1083a6f4ea6f2bfec09980c958fbd6f9e7c1cc5700744b51e2340

test:
  secret_key_base: c69a9d69787a4e8a9cf1236e36150ca825605c486b2acd83d58e1f5d6620951539bc6d800dced3d70b4d1199abfd5106a83ad2a1644c885004d35e2dd923403f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
